CREATE TABLE xxnbty.xxnbty_pegging_temp_tbl
(
	 record_id				    NUMBER
	,item_rm 				    VARCHAR2(250)
	,item_desc_rm 			  	VARCHAR2(240)
	,org_code_rm 			    VARCHAR2(7)
	,org_desc_rm 			    VARCHAR2(255)
	,excess_qty_rm 		    	NUMBER
	,order_type_rm 		    	VARCHAR2(4000)
	,due_date_rm 			    DATE
	,lot_number_rm 		    	VARCHAR2(80)
	,psd_expiry_date_rm   		DATE
	,order_number_rm 		  	VARCHAR2(4000)
	,source_org_rm			  	VARCHAR2(4000)
	,order_qty_rm			    NUMBER
	,pegging_order_no_rm  		VARCHAR2(4000)
	,item_bl 				    VARCHAR2(250)
	,item_desc_bl 			  	VARCHAR2(240)
	,org_code_bl 			    VARCHAR2(7)
	,org_desc_bl 			    VARCHAR2(255)
	,excess_qty_bl 		    	NUMBER
	,order_type_bl 		    	VARCHAR2(4000)
	,due_date_bl 			    DATE
	,lot_number_bl 		    	VARCHAR2(80)
	,psd_expiry_date_bl 		DATE
	,order_number_bl 		  	VARCHAR2(4000)
	,source_org_bl			  	VARCHAR2(4000)
	,order_qty_bl			    NUMBER
	,pegging_order_no_bl  		VARCHAR2(4000)
	,item_bc 				    VARCHAR2(250)
	,item_desc_bc 			  	VARCHAR2(240)
	,org_code_bc 			    VARCHAR2(7)
	,org_desc_bc 			    VARCHAR2(255)
	,excess_qty_bc 		    	NUMBER
	,order_type_bc 		    	VARCHAR2(4000)
	,due_date_bc 			    DATE
	,lot_number_bc 		    	VARCHAR2(80)
	,psd_expiry_date_bc 		DATE
	,order_number_bc 		  	VARCHAR2(4000)
	,source_org_bc			  	VARCHAR2(4000)
	,order_qty_bc			    NUMBER
	,pegging_order_no_bc  		VARCHAR2(4000)
	,item_fg 				    VARCHAR2(250)
	,item_desc_fg 			  	VARCHAR2(240)
	,org_code_fg 			    VARCHAR2(7)
	,org_desc_fg 			    VARCHAR2(255)
	,excess_qty_fg 		    	NUMBER
	,order_type_fg 		    	VARCHAR2(4000)
	,due_date_fg 			    DATE
	,lot_number_fg 		    	VARCHAR2(80)
	,psd_expiry_date_fg 		DATE
	,order_number_fg 		  	VARCHAR2(4000)
	,source_org_fg			  	VARCHAR2(4000)
	,order_qty_fg			    NUMBER
	,pegging_order_no_fg  		VARCHAR2(4000)
	,item_dd 				    VARCHAR2(250)
	,item_desc_dd 			  	VARCHAR2(240)
	,org_code_dd 			    VARCHAR2(7)
	,org_desc_dd 			    VARCHAR2(255)
	,excess_qty_dd 		    	NUMBER
	,order_type_dd 		    	VARCHAR2(4000)
	,due_date_dd 			    DATE
	,lot_number_dd 		    	VARCHAR2(80)
	,psd_expiry_date_dd 		DATE
	,order_number_dd 		  	VARCHAR2(4000)
	,source_org_dd			  	VARCHAR2(4000)
	,order_qty_dd			    NUMBER
	,pegging_order_no_dd  		VARCHAR2(4000)
	,last_update_date     		DATE           
	,last_updated_by      		NUMBER         
	,last_update_login    		NUMBER         
	,creation_date        		DATE           
	,created_by           		NUMBER	
	,request_id           		NUMBER
	,pegging_id					NUMBER
);
--[PUBLIC SYNONYM xxnbty_pegging_temp_tbl]
CREATE OR REPLACE PUBLIC SYNONYM xxnbty_pegging_temp_tbl for xxnbty.xxnbty_pegging_temp_tbl;
